name: Node
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Node
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@master
        with:
          always-auth: true
          registry-url: 'https://npm.pkg.github.com'
          scope: '@airthium'
      - name: Install
        run: yarn install
      - name: Depcheck
        run: yarn depcheck
      - name: Lint
        run: yarn prettier
      - name: Doc
        run: yarn doc
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
